// =============================================================================
// WHAT'S NEW & UPDATED
// Auto-generated by the Empire-HQ n8n publisher. Entries are prepended here
// whenever a lesson is published (NEW) or an existing lesson is refreshed
// (UPDATED). The home page renders the latest entries from this array.
// =============================================================================

export interface SiteUpdate {
  id: string
  title: string
  description: string
  date: string
  kind: "new" | "updated"
  href: string
}

export const ALL_UPDATES: SiteUpdate[] = [
  {
    "id": "decoding-digital-footprints-navigating-online-presence-new-2026-08-12",
    "title": "Decoding Digital Footprints: Navigating Your Online Presence",
    "description": "New lesson: Learn to identify, understand, and manage the personal data you leave online, empowering you to protect your digital identity.",
    "date": "2026-08-12",
    "kind": "new",
    "href": "/learn/decoding-digital-footprints-navigating-online-presence"
  },
  {
    "id": "zero-trust-architecture-for-small-businesses-new-2026-08-12",
    "title": "Zero Trust Architecture for Small Businesses: What It Is and How to Start",
    "description": "New lesson: An introductory guide to Zero Trust Architecture (ZTA) specifically tailored for small businesses, explaining its core principles and providing actionable steps for implementation.",
    "date": "2026-08-12",
    "kind": "new",
    "href": "/learn/zero-trust-architecture-for-small-businesses"
  },
]

export const latestUpdates = ALL_UPDATES.slice(0, 5)
