// =============================================================================
// WHAT'S NEW & UPDATED
// Auto-generated by the Empire-HQ n8n publisher. Entries are prepended here
// whenever a lesson is published (NEW) or an existing lesson is refreshed
// (UPDATED). The home page renders the latest entries from this array.
// =============================================================================

export interface SiteUpdate {
  id: string
  title: string
  description: string
  date: string
  kind: "new" | "updated"
  href: string
}

export const ALL_UPDATES: SiteUpdate[] = [
  {
    "id": "cis-nist-30-day-starter-new-2026-08-14",
    "title": "This Month's CIS/NIST Starter",
    "description": "New lesson: a 30-day control list — accounts, mail, backups, and a phone tree. Not a framework essay.",
    "date": "2026-08-14",
    "kind": "new",
    "href": "/learn/cis-nist-30-day-starter"
  },
  {
    "id": "email-m365-hygiene-new-2026-08-14",
    "title": "Email and Microsoft 365 Hygiene for Small Teams",
    "description": "New lesson: MFA on admins, inbox rules, legacy auth, and sharing links that expire.",
    "date": "2026-08-14",
    "kind": "new",
    "href": "/learn/email-m365-hygiene"
  },
  {
    "id": "ransomware-first-hour-new-2026-08-14",
    "title": "Ransomware: The First Hour",
    "description": "New lesson: isolate, tell the right people, preserve evidence. What not to do in hour one.",
    "date": "2026-08-14",
    "kind": "new",
    "href": "/learn/ransomware-first-hour"
  },
  {
    "id": "backups-that-actually-restore-new-2026-08-14",
    "title": "Backups That Actually Restore",
    "description": "New lesson: 3-2-1 copies, one off-reach backup, and a restore you have watched succeed.",
    "date": "2026-08-14",
    "kind": "new",
    "href": "/learn/backups-that-actually-restore"
  },
  {
    "id": "mfa-beyond-passwords-new-2026-08-14",
    "title": "MFA Beyond Passwords",
    "description": "New lesson: authenticators, number matching, and phishing-resistant passkeys.",
    "date": "2026-08-14",
    "kind": "new",
    "href": "/learn/mfa-beyond-passwords"
  },
  {
    "id": "whats-the-play-new-2026-08-13",
    "title": "What's the play",
    "description": "New layer on the lesson archive: paste an is-this-phishing scenario, get a plain-English ABC walkthrough with citations. Education only.",
    "date": "2026-08-13",
    "kind": "new",
    "href": "/whats-the-play"
  },
  {
    "id": "decoding-digital-footprints-navigating-online-presence-new-2026-08-12",
    "title": "Decoding Digital Footprints: Navigating Your Online Presence",
    "description": "New lesson: Learn to identify, understand, and manage the personal data you leave online, empowering you to protect your digital identity.",
    "date": "2026-08-12",
    "kind": "new",
    "href": "/learn/decoding-digital-footprints-navigating-online-presence"
  },
  {
    "id": "zero-trust-architecture-for-small-businesses-new-2026-08-12",
    "title": "Zero Trust Architecture for Small Businesses: What It Is and How to Start",
    "description": "New lesson: An introductory guide to Zero Trust Architecture (ZTA) specifically tailored for small businesses, explaining its core principles and providing actionable steps for implementation.",
    "date": "2026-08-12",
    "kind": "new",
    "href": "/learn/zero-trust-architecture-for-small-businesses"
  },
]

export const latestUpdates = ALL_UPDATES.slice(0, 5)
